In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Analytics Layer Initialized")

Analytics Layer Initialized

In [2]:
df = pd.read_parquet(
    "/Users/bibhrajsaha/uk-housing-intelligence-platform/data/processed/housing_master_dataset.parquet"
)

print(df.shape)

df.head()

(2816596, 35)

,transaction_id,price,transfer_date,postcode,property_type,old_new,duration,paon,saon,street,locality,town_city,district,county,ppd_category_type,record_status,source_file,property_type_description,ownership_type,property_age_type,transfer_year,transfer_month,latitude,longitude,lsoa_code,msoa_code,local_authority_code,country_code,deprivation_index,total_crimes,high_severity_crimes,medium_severity_crimes,low_severity_crimes,crime_score,price_to_crime_ratio
0,{01EB45F0-6229-40F3-E063-4704A8C05FDE},208000,2023-06-14,RH15 0DZ,F,N,L,62,NaN,THE WARREN,NaN,BURGESS HILL,MID SUSSEX,WEST SUSSEX,A,A,pp-2023.csv,Flat/Maisonette,Leasehold,Existing Property,2023,6,50.949219,-0.117541,E01031702,E02006618,E07000228,E92000001,31455.0,1.0,0.0,1.0,0.0,1.0,104000.000000
1,{01EB45F0-622A-40F3-E063-4704A8C05FDE},193000,2023-02-10,BN13 1NT,F,N,L,"CATHERINE LODGE, 52",FLAT 31,BOLSOVER ROAD,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A,pp-2023.csv,Flat/Maisonette,Leasehold,Existing Property,2023,2,50.819570,-0.408279,E01034828,E02006627,E07000229,E92000001,20871.0,0.0,0.0,0.0,0.0,0.0,193000.000000
2,{01EB45F0-622B-40F3-E063-4704A8C05FDE},185000,2023-05-26,BN11 2BU,F,N,L,MARIK MEWS,FLAT 3,SELDEN LANE,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A,pp-2023.csv,Flat/Maisonette,Leasehold,Existing Property,2023,5,50.813195,-0.358316,E01031835,E02006631,E07000229,E92000001,15307.0,10.0,4.0,5.0,1.0,10.0,16818.181818
3,{01EB45F0-622C-40F3-E063-4704A8C05FDE},187500,2023-06-09,BN16 3BJ,F,N,L,ABBOTSWOOD,FLAT 34,STATION ROAD,RUSTINGTON,LITTLEHAMPTON,ARUN,WEST SUSSEX,A,A,pp-2023.csv,Flat/Maisonette,Leasehold,Existing Property,2023,6,50.812921,-0.503186,E01031457,E02006551,E07000224,E92000001,20429.0,8.0,2.0,2.0,4.0,8.0,20833.333333
4,{01EB45F0-622D-40F3-E063-4704A8C05FDE},265000,2023-06-28,BN11 4JS,F,N,L,"ASPEN COURT, 40 - 42",FLAT 9,ST BOTOLPHS ROAD,NaN,WORTHING,WORTHING,WEST SUSSEX,A,A,pp-2023.csv,Flat/Maisonette,Leasehold,Existing Property,2023,6,50.817802,-0.387556,E01031810,E02006630,E07000229,E92000001,14756.0,23.0,10.0,7.0,5.0,23.0,11041.666667

In [3]:
print(df.columns.tolist())

['transaction_id', 'price', 'transfer_date', 'postcode', 'property_type', 'old_new', 'duration', 'paon', 'saon', 'street', 'locality', 'town_city', 'district', 'county', 'ppd_category_type', 'record_status', 'source_file', 'property_type_description', 'ownership_type', 'property_age_type', 'transfer_year', 'transfer_month', 'latitude', 'longitude', 'lsoa_code', 'msoa_code', 'local_authority_code', 'country_code', 'deprivation_index', 'total_crimes', 'high_severity_crimes', 'medium_severity_crimes', 'low_severity_crimes', 'crime_score', 'price_to_crime_ratio']

In [4]:
df.describe()

,price,transfer_year,transfer_month,latitude,longitude,deprivation_index,total_crimes,high_severity_crimes,medium_severity_crimes,low_severity_crimes,crime_score,price_to_crime_ratio
count,2.816596e+06,2.816596e+06,2.816596e+06,2.809255e+06,2.809255e+06,2.809255e+06,2.816596e+06,2.816596e+06,2.816596e+06,2.816596e+06,2.816596e+06,2.816596e+06
mean,3.934916e+05,2.024113e+03,6.359682e+00,5.238398e+01,-1.352645e+00,1.662734e+04,1.432477e+01,5.659604e+00,5.626490e+00,2.776890e+00,1.432477e+01,7.331015e+04
std,1.257611e+06,9.038373e-01,3.466098e+00,1.154013e+00,1.313065e+00,9.592655e+03,2.402087e+01,8.045484e+00,1.175245e+01,5.472472e+00,2.402087e+01,3.551165e+05
min,1.000000e+00,2.023000e+03,1.000000e+00,4.989516e+01,-6.352711e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.555556e-02
25%,1.800000e+05,2.023000e+03,3.000000e+00,5.146785e+01,-2.237619e+00,8.621000e+03,4.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,4.000000e+00,1.300000e+04
50%,2.800000e+05,2.024000e+03,6.000000e+00,5.221650e+01,-1.383223e+00,1.709400e+04,9.000000e+00,4.000000e+00,3.000000e+00,1.000000e+00,9.000000e+00,3.000000e+04
75%,4.250000e+05,2.025000e+03,9.000000e+00,5.338959e+01,-2.669970e-01,2.485400e+04,1.700000e+01,7.000000e+00,6.000000e+00,3.000000e+00,1.700000e+01,7.115385e+04
max,7.930200e+08,2.026000e+03,1.200000e+01,5.579741e+01,1.759634e+00,3.284400e+04,7.420000e+02,2.380000e+02,3.630000e+02,2.780000e+02,7.420000e+02,1.904982e+08

In [5]:
area_df = (
    df.groupby("lsoa_code")
      .agg(
          average_price=("price", "mean"),
          median_price=("price", "median"),
          transaction_count=("price", "count"),
          average_crime=("total_crimes", "mean"),
          average_deprivation=("deprivation_index", "mean")
      )
      .reset_index()
)

area_df.head()

,lsoa_code,average_price,median_price,transaction_count,average_crime,average_deprivation
0,E01000001,1.070104e+06,910000.0,123,24.0,29199.0
1,E01000002,1.160117e+06,895000.0,119,32.0,30379.0
2,E01000003,1.049628e+06,650000.0,71,16.0,14915.0
3,E01000005,2.039055e+06,949636.0,116,93.0,8678.0
4,E01000006,3.946303e+05,430000.0,33,7.0,14486.0

In [6]:
print(area_df.shape)

(35671, 6)

# Affordability Analytics

The objective of affordability analytics is to identify areas where property prices are relatively affordable compared to other areas.

Lower property prices should result in higher affordability scores.

The initial implementation uses min-max normalization on median property prices.

## Affordability Score Version 1 (Min-Max Normalization)

Method:

1. Aggregate property transactions to area level (LSOA).
2. Calculate median property price for each area.
3. Apply min-max normalization.
4. Reverse the score so that lower prices receive higher scores.

Formula:

Affordability Score = 100 − Normalized Median Price

Expected Outcome:

- Cheapest area → Score near 100
- Most expensive area → Score near 0

Validation is required to determine whether the resulting score distribution is suitable for ranking purposes.

In [7]:
area_df["affordability_score"] = (
    100 -
    (
        (
            area_df["median_price"]
            -
            area_df["median_price"].min()
        )
        /
        (
            area_df["median_price"].max()
            -
            area_df["median_price"].min()
        )
    ) * 100
)

area_df[
    [
        "lsoa_code",
        "median_price",
        "affordability_score"
    ]
].head()

   lsoa_code  median_price  affordability_score
0  E01000001      910000.0            80.326603
1  E01000002      895000.0            80.657619
2  E01000003      650000.0            86.064217
3  E01000005      949636.0            79.451925
4  E01000006      430000.0            90.919122

## Validation Findings

The min-max affordability score produced a highly compressed distribution.

Observations:

- Mean score ≈ 93
- Most areas received scores between 90 and 100
- A small number of extremely expensive areas distorted the normalization range

Conclusion:

The score is mathematically correct but not suitable for ranking because it does not sufficiently differentiate between most areas.

## Affordability Score Version 2 (Percentile-Based)

To reduce the impact of extreme property price outliers, percentile ranking is used instead of direct min-max normalization.

Method:

1. Rank all areas by median property price.
2. Convert ranks into percentiles.
3. Reverse the percentile score so that lower-priced areas receive higher scores.

Advantages:

- Less sensitive to extreme values
- Produces a more balanced score distribution
- Better supports ranking and comparison between areas

In [19]:
area_df["affordability_percentile"] = (
    area_df["median_price"]
    .rank(pct=True)
)

area_df["affordability_score_v2"] = (
    100 -
    (area_df["affordability_percentile"] * 100)
)

area_df["affordability_score_v2"].describe()

count    35671.000000
mean        49.998598
std         28.867676
min          0.000000
25%         24.939026
50%         49.784138
75%         74.976872
max         99.997197
Name: affordability_score_v2, dtype: float64

## Final Affordability Scoring Decision

Percentile-based affordability scoring has been adopted as the production methodology.

Results:

- Mean score ≈ 50
- Balanced distribution across all areas
- Improved differentiation between neighbourhoods
- More suitable for area ranking and composite index calculations

The percentile-based affordability score will be used in all subsequent analytics layers, including:

- Growth Score
- Investment Score
- Housing Intelligence Index
- Area Ranking Engine

In [9]:
area_df.to_parquet(
    "../data/analytics/area_analytics_base.parquet",
    index=False
)

print("Area analytics base dataset saved")

Area analytics base dataset saved

# Crime Analytics

The objective of crime analytics is to identify safer areas based on recorded crime activity.

Lower crime levels should result in higher crime scores.

The initial implementation uses min-max normalization.

## Crime Score Version 1 (Min-Max Normalization)

Method:

1. Aggregate crime values to area level.
2. Calculate average crime per area.
3. Apply min-max normalization.
4. Reverse the score so that lower crime areas receive higher scores.

Formula:

Crime Score = 100 − Normalized Crime Rate

In [10]:
area_df["crime_score_v2"] = (
    100 -
    (
        (
            area_df["average_crime"]
            -
            area_df["average_crime"].min()
        )
        /
        (
            area_df["average_crime"].max()
            -
            area_df["average_crime"].min()
        )
    ) * 100
)

area_df[
    [
        "lsoa_code",
        "average_crime",
        "crime_score_v2"
    ]
].head()

   lsoa_code  average_crime  crime_score_v2
0  E01000001           24.0       96.765499
1  E01000002           32.0       95.687332
2  E01000003           16.0       97.843666
3  E01000005           93.0       87.466307
4  E01000006            7.0       99.056604

In [11]:
area_df["crime_score_v2"].describe()

count    35671.000000
mean        98.257817
std          2.600193
min          0.000000
25%         97.843666
50%         98.787062
75%         99.460916
max        100.000000
Name: crime_score_v2, dtype: float64

In [12]:
area_df[
    [
        "lsoa_code",
        "average_crime",
        "crime_score_v2"
    ]
].sort_values(
    by="crime_score_v2",
    ascending=False
).head(10)

       lsoa_code  average_crime  crime_score_v2
6011   E01006330            0.0           100.0
5499   E01005816            0.0           100.0
5507   E01005824            0.0           100.0
5506   E01005823            0.0           100.0
5505   E01005822            0.0           100.0
5504   E01005821            0.0           100.0
29212  E01030773            0.0           100.0
35206  W01001543            0.0           100.0
35205  W01001542            0.0           100.0
5503   E01005820            0.0           100.0

In [13]:
area_df[
    [
        "lsoa_code",
        "average_crime",
        "crime_score_v2"
    ]
].sort_values(
    by="crime_score_v2",
    ascending=True
).head(10)

       lsoa_code  average_crime  crime_score_v2
33709  E01035716          742.0        0.000000
31261  E01033010          623.0       16.037736
4480   E01004734          567.0       23.584906
4504   E01004763          547.0       26.280323
31058  E01032739          524.0       29.380054
35649  W01002019          484.0       34.770889
31803  E01033760          482.0       35.040431
2330   E01002444          480.0       35.309973
31699  E01033620          468.0       36.927224
32063  E01034022          460.0       38.005391

## Validation Findings

The min-max crime score showed severe compression.

Observations:

- Mean score ≈ 98
- Most areas received scores near 100
- A small number of high-crime outliers dominated the normalization range

Conclusion:

The score was not suitable for ranking because it failed to sufficiently separate most areas.

In [14]:
area_df.to_parquet(
    "../data/analytics/crime_scores.parquet",
    index=False
)

print("Crime scores saved")

Crime scores saved

## Crime Score Version 2 (Percentile-Based)

A percentile-based approach was introduced to reduce the influence of extreme crime outliers.

Method:

1. Rank areas by crime level.
2. Convert ranks into percentiles.
3. Reverse the percentile score so that safer areas receive higher scores.

Advantages:

- More robust against outliers
- Balanced score distribution
- Better support for ranking applications

In [15]:
area_df["crime_percentile"] = (
    area_df["average_crime"]
    .rank(pct=True)
)

area_df["crime_score_v3"] = (
    100 -
    (area_df["crime_percentile"] * 100)
)

area_df[
    [
        "average_crime",
        "crime_score_v2",
        "crime_score_v3"
    ]
].head()

   average_crime  crime_score_v2  crime_score_v3
0           24.0       96.765499       12.025175
1           32.0       95.687332        6.686104
2           16.0       97.843666       24.273219
3           93.0       87.466307        0.748507
4            7.0       99.056604       58.456449

In [16]:
area_df["crime_score_v3"].describe()

count    35671.000000
mean        49.998598
std         28.837403
min          0.000000
25%         24.273219
50%         48.205825
75%         75.687533
max         95.957500
Name: crime_score_v3, dtype: float64

## Final Crime Scoring Decision

Percentile-based crime scoring has been adopted as the production methodology.

Results:

- Mean score ≈ 50
- Balanced distribution
- Strong separation between safer and less safe areas
- Suitable for rankings and composite indexes

The percentile-based crime score will be used in:

- Growth Score calculations
- Investment Score calculations
- Housing Intelligence Index
- Area Ranking Engine

In [17]:
area_df.describe()

,average_price,median_price,transaction_count,average_crime,average_deprivation,affordability_score,crime_score_v2,crime_percentile,crime_score_v3
count,3.567100e+04,3.567100e+04,35671.000000,35671.000000,35671.000000,35671.000000,35671.000000,35671.000000,35671.000000
mean,3.949680e+05,3.285939e+05,78.754591,12.927000,15590.250318,93.156925,98.257817,0.500014,49.998598
std,4.021287e+05,2.040563e+05,45.150391,19.293429,9833.413755,4.503062,2.600193,0.288374,28.837403
min,3.498015e+04,1.850000e+04,1.000000,0.000000,1.000000,0.000000,0.000000,0.040425,0.000000
25%,2.218883e+05,1.990000e+05,53.000000,4.000000,6862.500000,91.470815,97.843666,0.243125,24.273219
50%,3.191451e+05,2.850000e+05,70.000000,9.000000,15503.000000,94.118945,98.787062,0.517942,48.205825
75%,4.617578e+05,4.050000e+05,93.000000,16.000000,24110.500000,96.016771,99.460916,0.757268,75.687533
max,3.239720e+07,4.550000e+06,1009.000000,742.000000,32844.000000,100.000000,100.000000,1.000000,95.957500

# Growth Score Engine

Growth Score combines multiple indicators to estimate an area's future potential.

Components:

- Affordability
- Safety
- Deprivation Opportunity
- Market Activity

In [20]:
area_df["market_activity_score"] = (
    area_df["transaction_count"]
    .rank(pct=True)
    * 100
)

area_df["market_activity_score"].describe()

count    35671.000000
mean        50.001402
std         28.866365
min          0.009812
25%         25.327297
50%         49.419697
75%         74.835300
max        100.000000
Name: market_activity_score, dtype: float64

In [21]:
area_df["deprivation_opportunity_score"] = (
    area_df["average_deprivation"]
    .rank(pct=True)
    * 100
)

area_df["deprivation_opportunity_score"].describe()

count    35671.000000
mean        50.001402
std         28.867918
min          0.004205
25%         25.002103
50%         50.001402
75%         75.000701
max        100.000000
Name: deprivation_opportunity_score, dtype: float64

In [23]:
area_df["growth_score"] = (
    area_df["affordability_score_v2"] * 0.35
    +
    area_df["crime_score_v3"] * 0.25
    +
    area_df["deprivation_opportunity_score"] * 0.25
    +
    area_df["market_activity_score"] * 0.15
)

area_df[
    [
        "lsoa_code",
        "growth_score"
    ]
].head()

   lsoa_code  growth_score
0  E01000001     39.421939
1  E01000002     38.796642
2  E01000003     27.670096
3  E01000005     21.339814
4  E01000006     34.772504

In [24]:
area_df["growth_score"].describe()

count    35671.000000
mean        49.999720
std         13.128434
min          6.453211
25%         41.503147
50%         50.755936
75%         59.264494
max         88.059628
Name: growth_score, dtype: float64

In [25]:
area_df[
    [
        "lsoa_code",
        "growth_score"
    ]
].sort_values(
    by="growth_score",
    ascending=False
).head(20)

       lsoa_code  growth_score
32036  E01033995     88.059628
31643  E01033534     87.708923
19560  E01020605     86.819335
31034  E01032706     86.616790
4513   E01004773     86.083303
5926   E01006245     85.661532
19651  E01020698     85.494660
32037  E01033996     85.207241
4648   E01004910     84.788834
8112   E01008527     84.776639
32801  E01034763     84.696112
31619  E01033495     84.693799
5924   E01006243     84.692187
5980   E01006299     84.548162
32376  E01034338     84.480110
18246  E01019238     84.257240
8338   E01008760     84.053223
33180  E01035186     83.961341
5962   E01006281     83.918659
12274  E01012926     83.898265

In [26]:
area_df.to_parquet(
    "../data/analytics/growth_scores.parquet",
    index=False
)

print("Growth scores saved")

Growth scores saved

In [27]:
area_df[
    [
        "lsoa_code",
        "growth_score"
    ]
].sort_values(
    by="growth_score",
    ascending=False
).head(20)

       lsoa_code  growth_score
32036  E01033995     88.059628
31643  E01033534     87.708923
19560  E01020605     86.819335
31034  E01032706     86.616790
4513   E01004773     86.083303
5926   E01006245     85.661532
19651  E01020698     85.494660
32037  E01033996     85.207241
4648   E01004910     84.788834
8112   E01008527     84.776639
32801  E01034763     84.696112
31619  E01033495     84.693799
5924   E01006243     84.692187
5980   E01006299     84.548162
32376  E01034338     84.480110
18246  E01019238     84.257240
8338   E01008760     84.053223
33180  E01035186     83.961341
5962   E01006281     83.918659
12274  E01012926     83.898265

## Growth Score Validation

Validation results indicate that the composite score produces a healthy distribution.

Observations:

- Mean score ≈ 50
- Wide distribution across areas
- No severe score compression
- No dominant outlier effects

Conclusion:

The Growth Score is suitable for ranking and can be used as an input to higher-level analytics models.

In [28]:
investment_base = (
    df.groupby("lsoa_code")
      .agg(
          average_price_to_crime_ratio=(
              "price_to_crime_ratio",
              "mean"
          )
      )
      .reset_index()
)

In [29]:
area_df = area_df.merge(
    investment_base,
    on="lsoa_code",
    how="left"
)

print(area_df.shape)

(35671, 16)

In [30]:
area_df["investment_opportunity_score"] = (
    area_df["average_price_to_crime_ratio"]
    .rank(pct=True)
    * 100
)

In [32]:
area_df["investment_score"] = (
    area_df["growth_score"] * 0.40
    +
    area_df["affordability_score_v2"] * 0.25
    +
    area_df["crime_score_v3"] * 0.20
    +
    area_df["investment_opportunity_score"] * 0.15
)

In [33]:
area_df["investment_score"].describe()

count    35671.000000
mean        49.999467
std         14.380103
min          5.999944
25%         40.605940
50%         49.693617
75%         59.626636
max         89.644473
Name: investment_score, dtype: float64

In [34]:
area_df[
    [
        "lsoa_code",
        "investment_score"
    ]
].sort_values(
    by="investment_score",
    ascending=False
).head(20)

       lsoa_code  investment_score
5926   E01006245         89.644473
4648   E01004910         89.326722
4513   E01004773         89.230986
6030   E01006349         88.996650
32801  E01034763         88.881528
4507   E01004767         88.104735
5980   E01006299         87.982801
8153   E01008570         87.938437
12119  E01012760         87.867385
31188  E01032914         87.654762
6013   E01006332         87.631157
5904   E01006223         87.568165
5975   E01006294         87.515881
5207   E01005507         87.456365
5924   E01006243         87.244316
4622   E01004883         87.234392
5952   E01006271         87.209918
5909   E01006228         87.142497
12258  E01012909         87.127050
5938   E01006257         87.123882

In [35]:
area_df.to_parquet(
    "../data/analytics/investment_scores.parquet",
    index=False
)

print("Investment scores saved")

Investment scores saved

In [36]:
area_df = area_df.rename(
    columns={
        "affordability_score_v2": "affordability_score",
        "crime_score_v3": "crime_score"
    }
)

In [37]:
[
    col
    for col in area_df.columns
    if "score" in col
]

['affordability_score',
 'crime_score_v2',
 'crime_score',
 'affordability_score',
 'market_activity_score',
 'deprivation_opportunity_score',
 'growth_score',
 'investment_opportunity_score',
 'investment_score']

In [38]:
for i, col in enumerate(area_df.columns):
    print(i, col)

0 lsoa_code
1 average_price
2 median_price
3 transaction_count
4 average_crime
5 average_deprivation
6 affordability_score
7 crime_score_v2
8 crime_percentile
9 crime_score
10 affordability_percentile
11 affordability_score
12 market_activity_score
13 deprivation_opportunity_score
14 growth_score
15 average_price_to_crime_ratio
16 investment_opportunity_score
17 investment_score

In [46]:
list(enumerate(area_df.columns))

[(0, 'lsoa_code'),
 (1, 'average_price'),
 (2, 'median_price'),
 (3, 'transaction_count'),
 (4, 'average_crime'),
 (5, 'average_deprivation'),
 (6, 'crime_score'),
 (7, 'affordability_score'),
 (8, 'market_activity_score'),
 (9, 'deprivation_opportunity_score'),
 (10, 'growth_score'),
 (11, 'average_price_to_crime_ratio'),
 (12, 'investment_opportunity_score'),
 (13, 'investment_score')]

In [40]:
# Keep only the second affordability_score
# (the percentile-based version)

cols = []

affordability_count = 0

for col in area_df.columns:
    if col == "affordability_score":
        affordability_count += 1

        if affordability_count == 1:
            continue

    cols.append(col)

area_df = area_df.loc[:, cols]

In [45]:
area_df = area_df.drop(
    columns=[
        "crime_score_v2",
        "crime_percentile",
        "affordability_percentile"
    ]
)

In [42]:
area_df.iloc[:, [10, 11]].head()

   affordability_score  affordability_score
0            80.326603             1.567099
1            80.657619             1.683440
2            86.064217             5.498865
3            79.451925             1.351238
4            90.919122            21.188080

In [43]:
# Keep all columns except the first affordability_score

area_df = area_df.iloc[
    :,
    [0,1,2,3,4,5,6,7,8,9,11,12,13,14,15,16,17]
]

# Housing Intelligence Index (HII)

The Housing Intelligence Index is the master score of the UK Housing Intelligence Platform.

Purpose:

Provide a single overall measure of area attractiveness by combining multiple analytical dimensions.

Inputs:

- Affordability Score
- Crime Score
- Growth Score
- Investment Score

The index is designed to support:

- Area comparison
- Area ranking
- Investment discovery
- Dashboard visualisation

## Housing Intelligence Index Weighting

| Component | Weight |
|------------|----------|
| Affordability Score | 25% |
| Crime Score | 20% |
| Growth Score | 25% |
| Investment Score | 30% |

Total Weight = 100%

In [47]:
area_df["housing_intelligence_index"] = (
    area_df["affordability_score"] * 0.25
    +
    area_df["crime_score"] * 0.20
    +
    area_df["growth_score"] * 0.25
    +
    area_df["investment_score"] * 0.30
)

In [48]:
area_df["housing_intelligence_index"].describe()

count    35671.000000
mean        49.999139
std         15.216734
min          4.957871
25%         40.206239
50%         50.298413
75%         60.224325
max         90.380286
Name: housing_intelligence_index, dtype: float64

In [49]:
area_df[
    [
        "lsoa_code",
        "housing_intelligence_index"
    ]
].sort_values(
    by="housing_intelligence_index",
    ascending=False
).head(20)

       lsoa_code  housing_intelligence_index
4648   E01004910                   90.380286
5926   E01006245                   90.257507
4513   E01004773                   90.136930
12119  E01012760                   90.045405
6030   E01006349                   89.862349
32801  E01034763                   89.787268
4507   E01004767                   89.418283
5975   E01006294                   88.720896
5909   E01006228                   88.612840
31643  E01033534                   88.577263
5904   E01006223                   88.553747
6013   E01006332                   88.489278
6016   E01006335                   88.299616
5938   E01006257                   88.206388
6036   E01006355                   88.188065
5207   E01005507                   88.099995
8335   E01008757                   88.070533
4670   E01004932                   88.035998
5952   E01006271                   88.023941
6068   E01006387                   88.017609

In [50]:
area_df[
    [
        "lsoa_code",
        "housing_intelligence_index"
    ]
].sort_values(
    by="housing_intelligence_index",
    ascending=True
).head(20)

       lsoa_code  housing_intelligence_index
1801   E01001899                    4.957871
826    E01000863                    5.011205
1749   E01001846                    5.812298
821    E01000858                    6.079530
4059   E01004286                    6.770198
1949   E01002051                    6.905677
31680  E01033594                    6.972229
1714   E01001808                    7.201302
899    E01000939                    7.284194
3326   E01003486                    7.405561
2871   E01003017                    7.427423
2762   E01002906                    7.602548
4449   E01004702                    7.615049
1307   E01001361                    7.632060
898    E01000938                    7.875481
2735   E01002878                    7.908702
2688   E01002830                    7.963454
4480   E01004734                    8.022750
817    E01000853                    8.052937
2578   E01002713                    8.144190

In [51]:
area_df["area_rank"] = (
    area_df["housing_intelligence_index"]
    .rank(
        ascending=False,
        method="dense"
    )
)

In [52]:
area_df["percentile_rank"] = (
    area_df["housing_intelligence_index"]
    .rank(pct=True)
    * 100
)

In [53]:
area_df[
    [
        "lsoa_code",
        "housing_intelligence_index",
        "area_rank",
        "percentile_rank"
    ]
].sort_values(
    by="area_rank"
).head(20)

       lsoa_code  housing_intelligence_index  area_rank  percentile_rank
4648   E01004910                   90.380286        1.0       100.000000
5926   E01006245                   90.257507        2.0        99.997197
4513   E01004773                   90.136930        3.0        99.994393
12119  E01012760                   90.045405        4.0        99.991590
6030   E01006349                   89.862349        5.0        99.988786
32801  E01034763                   89.787268        6.0        99.985983
4507   E01004767                   89.418283        7.0        99.983180
5975   E01006294                   88.720896        8.0        99.980376
5909   E01006228                   88.612840        9.0        99.977573
31643  E01033534                   88.577263       10.0        99.974769
5904   E01006223                   88.553747       11.0        99.971966
6013   E01006332                   88.489278       12.0        99.969163
6016   E01006335                   88.299616       13.0        99.966359
5938   E01006257                   88.206388       14.0        99.963556
6036   E01006355                   88.188065       15.0        99.960752
5207   E01005507                   88.099995       16.0        99.957949
8335   E01008757                   88.070533       17.0        99.955146
4670   E01004932                   88.035998       18.0        99.952342
5952   E01006271                   88.023941       19.0        99.949539
6068   E01006387                   88.017609       20.0        99.946735

In [54]:
area_df.to_parquet(
    "../data/analytics/housing_intelligence.parquet",
    index=False
)

print("Housing Intelligence dataset saved")

Housing Intelligence dataset saved

Ranking Engine

In [55]:
top_100_areas = (
    area_df
    .sort_values(
        by="housing_intelligence_index",
        ascending=False
    )
    .head(100)
)

top_100_areas.head()

,lsoa_code,average_price,median_price,transaction_count,average_crime,average_deprivation,crime_score,affordability_score,market_activity_score,deprivation_opportunity_score,growth_score,average_price_to_crime_ratio,investment_opportunity_score,investment_score,housing_intelligence_index,area_rank,percentile_rank
4648,E01004910,152128.225806,130750.0,124,0.0,18706.0,95.9575,92.774242,90.050741,59.283452,84.788834,152128.225806,86.840851,89.326722,90.380286,1.0,100.000000
5926,E01006245,182132.923529,140000.0,170,0.0,19401.0,95.9575,91.029127,96.497155,61.349556,85.661532,182132.923529,89.540523,89.644473,90.257507,2.0,99.997197
4513,E01004773,147224.047337,142000.0,169,0.0,20211.0,95.9575,90.621233,96.406044,63.662359,86.083303,147224.047337,86.339043,89.230986,90.136930,3.0,99.994393
12119,E01012760,106814.795455,100000.0,132,0.0,10092.0,95.9575,97.492361,91.878557,34.355639,80.482395,106814.795455,80.732247,87.867385,90.045405,4.0,99.991590
6030,E01006349,191319.027397,125500.0,146,0.0,13448.0,95.9575,93.889995,94.217992,44.055395,81.997421,191319.027397,90.224552,88.996650,89.862349,5.0,99.988786

In [56]:
bottom_100_areas = (
    area_df
    .sort_values(
        by="housing_intelligence_index",
        ascending=True
    )
    .head(100)
)

bottom_100_areas.head()

,lsoa_code,average_price,median_price,transaction_count,average_crime,average_deprivation,crime_score,affordability_score,market_activity_score,deprivation_opportunity_score,growth_score,average_price_to_crime_ratio,investment_opportunity_score,investment_score,housing_intelligence_index,area_rank,percentile_rank
1801,E01001899,7.193882e+05,735000.0,49,81.0,3413.0,0.992403,3.526674,20.344257,15.107510,8.310953,8773.026381,10.636091,5.999944,4.957871,35669.0,0.002803
826,E01000863,1.768851e+06,925000.0,54,160.0,6114.0,0.229879,1.461972,26.619663,22.842085,10.272630,10986.649298,15.009391,6.771930,5.011205,35668.0,0.005607
1749,E01001846,5.814820e+05,650000.0,25,46.0,2705.0,3.240728,5.498865,3.002439,13.072244,6.453211,12371.957447,17.664209,7.253778,5.812298,35667.0,0.008410
821,E01000858,1.150787e+06,705000.0,21,53.0,4987.0,2.380085,4.119593,1.759132,19.598553,7.200387,21310.864198,32.393261,9.245059,6.079530,35666.0,0.011214
4059,E01004286,7.516176e+05,822500.0,34,35.0,5381.0,5.598385,2.314205,7.120630,20.750750,8.465350,20878.267974,31.784923,9.852107,6.770198,35665.0,0.014017

In [57]:
rankings_df = area_df[
    [
        "lsoa_code",
        "housing_intelligence_index",
        "area_rank",
        "percentile_rank"
    ]
].copy()

rankings_df.head()

   lsoa_code  housing_intelligence_index  area_rank  percentile_rank
0  E01000001                   20.735945    34448.0         3.425752
1  E01000002                   18.853615    34767.0         2.531468
2  E01000003                   21.369702    34304.0         3.829441
3  E01000005                   10.012423    35585.0         0.238289
4  E01000006                   37.676037    28376.0        20.449385

In [58]:
rankings_df.to_parquet(
    "../data/analytics/rankings.parquet",
    index=False
)

print("Rankings dataset saved")

Rankings dataset saved

In [59]:
top_100_areas.to_parquet(
    "../data/analytics/top_100_areas.parquet",
    index=False
)

bottom_100_areas.to_parquet(
    "../data/analytics/bottom_100_areas.parquet",
    index=False
)

print("Leaderboards saved")

Leaderboards saved

In [60]:
print("UK Housing Intelligence Platform")
print("-" * 40)

print(f"Areas Analysed: {len(area_df):,}")

print(
    f"Top HII Score: "
    f"{area_df['housing_intelligence_index'].max():.2f}"
)

print(
    f"Lowest HII Score: "
    f"{area_df['housing_intelligence_index'].min():.2f}"
)

print(
    f"Average HII Score: "
    f"{area_df['housing_intelligence_index'].mean():.2f}"
)

UK Housing Intelligence Platform
----------------------------------------
Areas Analysed: 35,671
Top HII Score: 90.38
Lowest HII Score: 4.96
Average HII Score: 50.00

In [61]:
rankings_df.shape

(35671, 4)

In [62]:
# Final Analytics Export Refresh

area_df.to_parquet(
    "../data/analytics/housing_intelligence.parquet",
    index=False
)

rankings_df.to_parquet(
    "../data/analytics/rankings.parquet",
    index=False
)

top_100_areas.to_parquet(
    "../data/analytics/top_100_areas.parquet",
    index=False
)

bottom_100_areas.to_parquet(
    "../data/analytics/bottom_100_areas.parquet",
    index=False
)

print("Final analytics exports refreshed")

Final analytics exports refreshed